project:
  type: website

website:
  page-navigation: true
  title: "R for Palaeobiologists"
  description: "Palaeoverse: Workshop and Hackathon - University College London, Autumn 2023"
  site-url: "https://hackathon.palaeoverse.org"

  repo-url: https://hackathon.palaeoverse.org
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@LewisAlanJones"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Lewis A. Jones"
    background: "lightgrey"

  sidebar:
    background: "lightgrey"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/palaeoverse-community
        text: "GitHub organization"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: overview.qmd
            text: Overview
      - section: "Day 1"
        contents:
          - href: day-one.qmd
            text: Day One
      - section: "Day 2"
        contents:
          - href: day-two.qmd
            text: Day Two
      - section: "Useful information"
        contents:
          - href: local.qmd
            text: Local Information
      - href: conduct.qmd
        text: Code of Conduct

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual